[application]
name = "hours-ui"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Hours"

[web.resource]
style = ["assets/tailwind.css"]

[web.resource.dev]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[tool.dioxus.tailwind]
input = "tailwind.css"
output = "assets/tailwind.css"